In [270]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
import numpy as np
from sklearn import set_config
set_config(transform_output="pandas")
warnings.simplefilter('ignore')
# import plotly.express as px

In [206]:
df = pd.read_csv("data/AQUASTAT_complete.csv", index_col=0)

In [207]:
df.head()

,Country,M49,Variable,Year,Unit,Symbol,Symbol Description,Value
0,Samoa,882,Total area of the country (excl. coastal water),2020,1000 ha,E,Estimate either calculated as sum or identify ...,279.000000
1,Samoa,882,Cultivated area (arable land + permanent crops),2020,1000 ha,X,External value (reported by FAOSTAT or another...,43.000000
2,Samoa,882,Population density,2020,inhab/km2,E,Estimate either calculated as sum or identify ...,71.116129
3,Samoa,882,"Agriculture, value added (% GDP)",2020,%,X,External value (reported by FAOSTAT or another...,10.543126
4,Samoa,882,Rural population with access to safe drinking-...,2020,%,I,"Imputed (carry forward, vertical imputation, l...",99.300000

create unit dict

In [208]:
def transform_name(col):
    col = col.replace("_(NRI)","")
    col = col.replace("_(GDP)","")
    col = col.replace("_(JMP)","")
    col = col.replace("_(IRWR)","")
    col = col.replace("SDG_6.4.1._","")
    col = col.replace("SDG_6.4.2._","")
    col = col.replace("-","_")
    col = col.replace(":","")
    col = col.replace(".","")
    col = col.replace(",","")
    col = col.replace("(","")
    col = col.replace(")","")
    col = col.lower()
    col = col.replace("+","plus")
    col = col.replace(" ","_")

    return col

In [209]:
unit_dict =  {}
for var in df.Variable.unique():
    var_trans = transform_name(var)
    unit_dict[var_trans] = df.query("Variable == @var")["Unit"].unique()[0]

In [210]:
unit_dict

{'total_area_of_the_country_excl_coastal_water': '1000 ha',
 'cultivated_area_arable_land_plus_permanent_crops': '1000 ha',
 'population_density': 'inhab/km2',
 'agriculture_value_added_%_gdp': '%',
 'rural_population_with_access_to_safe_drinking_water_jmp': '%',
 'groundwater_entering_the_country_total': '10^9 m3/year',
 'total_renewable_groundwater': '10^9 m3/year',
 'dam_capacity_per_capita': 'm3/inhab',
 'gdp_deflator_2015': nan,
 'arable_land_area': '1000 ha',
 'total_population_with_access_to_safe_drinking_water_jmp': '%',
 'urban_population_with_access_to_safe_drinking_water_jmp': '%',
 'surface_water_inflow_secured_through_treaties': '10^9 m3/year',
 'surface_water_accounted_inflow': '10^9 m3/year',
 'total_dam_capacity': 'km3',
 'produced_municipal_wastewater': '10^9 m3/year',
 'area_equipped_for_full_control_irrigation_sprinkler_irrigation': '1000 ha',
 '%_of_agricultural_water_managed_area_equipped_for_irrigation': '%',
 '%_of_area_equipped_for_irrigation_power_irrigated': '%',
 '%_of_the_cultivated_area_equipped_for_irrigation': '%',
 'harvested_irrigated_temporary_crop_area_maize': '1000 ha',
 'harvested_irrigated_temporary_crop_area_leguminous_crops': '1000 ha',
 'prevalence_of_undernourishment_3_year_average': '%',
 'interannual_variability_wri': nan,
 'services_value_added_to_gdp': 'current US$',
 'sdg_641_water_use_efficiency': 'US$/m3',
 'human_development_index_hdi_[highest_=_1]': nan,
 'surface_water_produced_internally': '10^9 m3/year',
 'area_equipped_for_full_control_irrigation_localized_irrigation': '1000 ha',
 '%_of_area_equipped_for_irrigation_by_mixed_surface_water_and_groundwater': '%',
 'area_equipped_for_power_irrigation_surface_water_or_groundwater': '1000 ha',
 'harvested_irrigated_permanent_crop_area_coffee': '1000 ha',
 'irrigated_cropping_intensity': '%',
 'national_rainfall_index_nri': 'mm/year',
 'seasonal_variability_wri': nan,
 'industry_value_added_to_gdp': 'current US$',
 'environmental_flow_requirements': '10^9 m3/year',
 'total_population': '1000 inhab',
 'rural_population': '1000 inhab',
 'total_internal_renewable_water_resources_per_capita': 'm3/inhab/year',
 'total_renewable_water_resources': '10^9 m3/year',
 'agricultural_water_withdrawal': '10^9 m3/year',
 'municipal_water_withdrawal': '10^9 m3/year',
 'agricultural_water_withdrawal_as_%_of_total_water_withdrawal': '%',
 'area_equipped_for_irrigation_by_groundwater': '1000 ha',
 'harvested_irrigated_temporary_crop_area_potatoes': '1000 ha',
 'area_equipped_for_full_control_irrigation_actually_irrigated': '1000 ha',
 '%_of_total_country_area_cultivated': '%',
 'water_withdrawal_for_livestock_watering_and_cleaning': '10^9 m3/year',
 'sdg_641_irrigated_agriculture_water_use_efficiency': 'US$/m3',
 'total_internal_renewable_water_resources_irwr': '10^9 m3/year',
 'surface_water_accounted_flow_of_border_rivers': '10^9 m3/year',
 'industrial_water_withdrawal': '10^9 m3/year',
 'municipal_water_withdrawal_as_%_of_total_withdrawal': '%',
 'total_cultivated_area_drained': '1000 ha',
 'non_irrigated_cultivated_area_drained': '1000 ha',
 '%_of_total_cultivated_area_drained': '%',
 'area_equipped_for_irrigation_by_surface_water': '1000 ha',
 '%_of_total_grain_production_irrigated': '%',
 'harvested_irrigated_temporary_crop_area_rice': '1000 ha',
 'harvested_irrigated_temporary_crop_area_vegetables': '1000 ha',
 'irrigation_water_withdrawal': '10^9 m3/year',
 'water_withdrawal_for_aquaculture': '10^9 m3/year',
 'overlap_between_surface_water_and_groundwater': '10^9 m3/year',
 'flood_occurrence_wri': nan,
 'sdg_642_water_stress': '%',
 'ratio_between_rainfed_and_irrigated_yields': nan,
 'groundwater_produced_internally': '10^9 m3/year',
 'surface_water_inflow_not_submitted_to_treaties': '10^9 m3/year',
 'surface_water_inflow_submitted_to_treaties': '10^9 m3/year',
 'surface_water_leaving_the_country_to_other_countries_total': '10^9 m3/year',
 'total_renewable_surface_water': '10^9 m3/year',
 'total_exploitable_water_resources': '10^9 m3/year',
 'treated_municipal_wastewater': '10^9 m3/year',
 'harvested_irrigated_temporary_crop_area_other_roots_and_tubers': '1000 ha',
 'groundwater_accounted_outflow_to_other_countries': '10^9 m3/year',
 'sdg_641_services_water_use_efficiency': 'US$/m3',
 'surface_water_outflow_to_other_countries_secured_through_treaties': '10^9 m3/year',
 'groundwater_leaving_the_country_to_other_countries_total': '10^9 m3/year',
 'area_equipped_for_full_control_irrigation_total': '1000 ha',
 'gdp_per_capita': 'current US$/inhab',
 'agriculture_value_added_to_gdp': 'current US$',
 '%_of_agricultural_gva_produced_by_irrigated_agriculture': '%',
 'permanent_crops_area': '1000 ha',
 'total_water_withdrawal': '10^9 m3/year',
 'total_water_withdrawal_per_capita': 'm3/inhab/year',
 'area_equipped_for_full_control_irrigation_surface_irrigation': '1000 ha',
 '%_of_the_area_equipped_for_irrigation_actually_irrigated': '%',
 'harvested_irrigated_temporary_crop_area_sweet_potatoes': '1000 ha',
 'harvested_irrigated_permanent_crop_area_plantains': '1000 ha',
 'harvested_irrigated_permanent_crop_area_oil_palm': '1000 ha',
 'harvested_irrigated_temporary_crop_area_other_crops': '1000 ha',
 'gender_inequality_index_gii_[equality_=_0;_inequality_=_1': nan,
 'long_term_average_annual_precipitation_in_depth': 'mm/year',
 'surface_water_entering_the_country_total': '10^9 m3/year',
 'surface_water_total_flow_of_border_rivers': '10^9 m3/year',
 'surface_water_outflow_to_other_countries_not_submitted_to_treaties': '10^9 m3/year',
 'surface_water_outflow_to_other_countries_submitted_to_treaties': '10^9 m3/year',
 'dependency_ratio': '%',
 'exploitable_regular_renewable_surface_water': '10^9 m3/year',
 'exploitable_irregular_renewable_surface_water': '10^9 m3/year',
 'exploitable_regular_renewable_groundwater': '10^9 m3/year',
 'irrigation_potential': '1000 ha',
 'groundwater_accounted_inflow': '10^9 m3/year',
 'exploitable_total_renewable_surface_water': '10^9 m3/year',
 'long_term_average_annual_precipitation_in_volume': '10^9 m3/year',
 'surface_water_total_external_renewable': '10^9 m3/year',
 'water_resources_total_external_renewable': '10^9 m3/year',
 'total_renewable_water_resources_per_capita': 'm3/inhab/year',
 '%_of_area_equipped_for_irrigation_by_groundwater_': '%',
 'area_equipped_for_irrigation_total': '1000 ha',
 'total_agricultural_water_managed_area': '1000 ha',
 'harvested_irrigated_temporary_crop_area_sugarcane': '1000 ha',
 'total_harvested_irrigated_crop_area_full_control_irrigation': '1000 ha',
 'urban_population': '1000 inhab',
 'gross_domestic_product_gdp': 'current US$',
 'industrial_water_withdrawal_as_%_of_total_water_withdrawal': '%',
 'irrigation_water_requirement': '10^9 m3/year',
 'fresh_surface_water_withdrawal': '10^9 m3/year',
 'fresh_groundwater_withdrawal': '10^9 m3/year',
 'total_freshwater_withdrawal': '10^9 m3/year',
 'desalinated_water_produced': '10^9 m3/year',
 'direct_use_of_treated_municipal_wastewater': '10^9 m3/year',
 'agricultural_water_withdrawal_as_%_of_total_renewable_water_resources': '%',
 'mdg_75_freshwater_withdrawal_as_%_of_total_renewable_water_resources': '%',
 'area_equipped_for_irrigation_drained': '1000 ha',
 'area_equipped_for_irrigation_equipped_lowland_areas': '1000 ha',
 'flood_recession_cropping_area_non_equipped': '1000 ha',
 'cultivated_wetlands_and_inland_valley_bottoms_non_equipped': '1000 ha',
 'area_equipped_for_irrigation_spate_irrigation': '1000 ha',
 'area_equipped_for_irrigation_actually_irrigated': '1000 ha',
 '%_of_area_equipped_for_irrigation_by_surface_water': '%',
 '%_of_irrigation_potential_equipped_for_irrigation': '%',
 'harvested_irrigated_temporary_crop_area_wheat': '1000 ha',
 'harvested_irrigated_temporary_crop_area_barley': '1000 ha',
 'harvested_irrigated_temporary_crop_area_other_cereals': '1000 ha',
 'harvested_irrigated_temporary_crop_area_sugar_beet': '1000 ha',
 'harvested_irrigated_permanent_crop_area_bananas': '1000 ha',
 'harvested_irrigated_permanent_crop_area_citrus': '1000 ha',
 'harvested_irrigated_temporary_crop_area_cotton': '1000 ha',
 'harvested_irrigated_temporary_crop_area_soybeans': '1000 ha',
 'harvested_irrigated_permanent_crop_area_other_crops': '1000 ha',
 'area_salinized_by_irrigation': '1000 ha',
 'area_waterlogged_by_irrigation': '1000 ha',
 '%_of_area_equipped_for_irrigation_salinized': '%',
 'water_withdrawal_for_cooling_of_thermoelectric_plants': '10^9 m3/year',
 '%_of_area_equipped_for_full_control_irrigation_actually_irrigated': '%',
 'area_equipped_for_irrigation_by_direct_use_of_treated_municipal_wastewater': '1000 ha',
 'permanent_meadows_and_pastures_irrigated': '1000 ha',
 'not_treated_municipal_wastewater': '10^9 m3/year',
 'treated_municipal_wastewater_discharged_secondary_water': '10^9 m3/year',
 'area_equipped_for_irrigation_by_direct_use_of_non_treated_municipal_wastewater_': '1000 ha',
 'number_of_municipal_wastewater_treatment_facilities': nan,
 'harvested_irrigated_temporary_crop_area_total': '1000 ha',
 'harvested_irrigated_permanent_crop_area_total': '1000 ha',
 'harvested_irrigated_permanent_crop_area_grass_and_fodder': '1000 ha',
 'area_equipped_for_irrigation_by_direct_use_of_not_treated_municipal_wastewater': '1000 ha',
 '%_of_the_agricultural_holdings_with_irrigation_managed_by_women': '%',
 'number_of_people_undernourished_3_year_average': '1000 inhab',
 'harvested_irrigated_temporary_crop_area_fodder': '1000 ha',
 '%_of_area_equipped_for_irrigation_drained': '%',
 '%_of_area_equipped_for_irrigation_by_direct_use_of__treated_municipal_wastewater': '%',
 'sdg_641_industrial_water_use_efficiency': 'US$/m3',
 'area_equipped_for_irrigation_by_mixed_surface_water_and_groundwater': '1000 ha',
 'harvested_irrigated_temporary_crop_area_millet': '1000 ha',
 'direct_use_of_agricultural_drainage_water': '10^9 m3/year',
 'harvested_irrigated_temporary_crop_area_sorghum': '1000 ha',
 'harvested_irrigated_temporary_crop_area_cassava': '1000 ha',
 'harvested_irrigated_temporary_crop_area_sunflower': '1000 ha',
 'harvested_irrigated_temporary_crop_area_flowers': '1000 ha',
 'population_affected_by_water_related_disease': '1000 inhab',
 'direct_use_of_treated_municipal_wastewater_for_irrigation_purposes': '10^9 m3/year',
 'collected_municipal_wastewater': '10^9 m3/year',
 'capacity_of_the_municipal_wastewater_treatment_facilities': '10^9 m3/year',
 'not_treated_municipal_wastewater_discharged_secondary_water': '10^9 m3/year',
 'harvested_irrigated_permanent_crop_area_other_fruits': '1000 ha',
 '%_of_the_area_equipped_for_irrigation_managed_by_women': '%',
 'harvested_irrigated_permanent_crop_area_grapes': '1000 ha',
 'harvested_irrigated_temporary_crop_area_tobacco': '1000 ha',
 '%_of_area_equipped_for_irrigation_by_direct_use_of_non_treated_municipal_wastewater': '%',
 'harvested_irrigated_permanent_crop_area_cocoa_beans': '1000 ha',
 'harvested_irrigated_permanent_crop_area_tea': '1000 ha',
 'harvested_irrigated_permanent_crop_area_rubber': '1000 ha',
 'harvested_irrigated_temporary_crop_area_groundnuts': '1000 ha',
 'harvested_irrigated_temporary_crop_area_sesame': '1000 ha',
 'direct_use_of_not_treated_municipal_wastewater_for_irrigation_purposes': '10^9 m3/year',
 'harvested_irrigated_permanent_crop_area_olives': '1000 ha',
 '%_of_area_equipped_for_irrigation_by_direct_use_of_agricultural_drainage_water_': '%',
 'harvested_irrigated_permanent_crop_area_coconuts': '1000 ha',
 'area_equipped_for_irrigation_by_direct_use_of_agricultural_drainage_water': '1000 ha',
 'area_equipped_for_irrigation_by_desalinated_water': '1000 ha',
 '%_of_area_equipped_for_irrigation_by_desalinated_water': '%'}

In [211]:
df.query("Variable=='Dam capacity per capita'")#.describe()

,Country,M49,Variable,Year,Unit,Symbol,Symbol Description,Value
7,Samoa,882,Dam capacity per capita,2020,m3/inhab,E,Estimate either calculated as sum or identify ...,50.399669
1002,South Africa,710,Dam capacity per capita,1968,m3/inhab,E,Estimate either calculated as sum or identify ...,151.367637
1003,Suriname,740,Dam capacity per capita,1968,m3/inhab,E,Estimate either calculated as sum or identify ...,56093.114570
1004,Niger,562,Dam capacity per capita,1968,m3/inhab,E,Estimate either calculated as sum or identify ...,1.822264
1005,Guyana,328,Dam capacity per capita,1968,m3/inhab,E,Estimate either calculated as sum or identify ...,265.264244
...,...,...,...,...,...,...,...,...
809229,Cameroon,120,Dam capacity per capita,2008,m3/inhab,E,Estimate either calculated as sum or identify ...,810.829160
809230,Jordan,400,Dam capacity per capita,2008,m3/inhab,E,Estimate either calculated as sum or identify ...,41.931049
809231,Turkmenistan,795,Dam capacity per capita,2008,m3/inhab,E,Estimate either calculated as sum or identify ...,1133.461122
809232,Azerbaijan,31,Dam capacity per capita,2008,m3/inhab,E,Estimate either calculated as sum or identify ...,2441.930415
809233,Venezuela (Bolivarian Republic of),862,Dam capacity per capita,2008,m3/inhab,E,Estimate either calculated as sum or identify ...,5703.671234

In [212]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 811078 entries, 0 to 811077
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Country             811078 non-null  object
 1   M49                 811078 non-null  int64
 2   Variable            811078 non-null  object
 3   Year                811078 non-null  int64
 4   Unit                779362 non-null  object
 5   Symbol              662333 non-null  object
 6   Symbol Description  811078 non-null  object
 7   Value               811078 non-null  float64
dtypes: float64(1), int64(2), object(5)
memory usage: 55.7+ MB

In [213]:
df.drop(columns=["M49", "Symbol", "Symbol Description"], inplace = True)

In [214]:
df.head()

,Country,Variable,Year,Unit,Value
0,Samoa,Total area of the country (excl. coastal water),2020,1000 ha,279.000000
1,Samoa,Cultivated area (arable land + permanent crops),2020,1000 ha,43.000000
2,Samoa,Population density,2020,inhab/km2,71.116129
3,Samoa,"Agriculture, value added (% GDP)",2020,%,10.543126
4,Samoa,Rural population with access to safe drinking-...,2020,%,99.300000

In [215]:
df.Country.nunique()

200

In [216]:
df.Year.nunique()

57

In [217]:
df.Variable.nunique()

193

In [218]:
targets = ["Total population with access to safe drinking-water (JMP)", "GDP per capita", "Water stress"]

filter for number of countries and number of years per variable

In [219]:
exclude_list = []
for var in df.Variable.unique()[:]:
    if var in targets:  continue
    df_temp = df.query("Variable==@var")
    if df_temp.Country.nunique()<=130 and df_temp.Year.nunique()<=30:
        print(var, ":")
        print("n countries: ", df_temp.Country.nunique())
        print("n years: ", df_temp.Year.nunique())
        # print(df_temp.isna().sum())
        # print(df_temp.isna().sum().max())
        print("")
        exclude_list.append(var)
    #display(df_temp)

Water withdrawal for livestock (watering and cleaning) :
n countries:  70
n years:  21

Water withdrawal for aquaculture :
n countries:  52
n years:  30

Harvested irrigated temporary crop area: Sweet potatoes :
n countries:  17
n years:  26

Harvested irrigated permanent crop area: Plantains :
n countries:  10
n years:  17

Number of people undernourished (3-year average) :
n countries:  120
n years:  29

% of area equipped for irrigation drained :
n countries:  50
n years:  30

Harvested irrigated temporary crop area: Millet :
n countries:  14
n years:  28

Direct use of agricultural drainage water :
n countries:  34
n years:  28

Harvested irrigated temporary crop area: Sorghum :
n countries:  31
n years:  29

Harvested irrigated temporary crop area: Cassava :
n countries:  9
n years:  24

Population affected by water related disease :
n countries:  32
n years:  29

Direct use of treated municipal wastewater for irrigation purposes :
n countries:  43
n years:  27

Harvested irrigated permanent crop area: Other fruits :
n countries:  62
n years:  28

Harvested irrigated permanent crop area: Cocoa beans :
n countries:  6
n years:  30

Harvested irrigated permanent crop area: Tea :
n countries:  12
n years:  22

Harvested irrigated permanent crop area: Rubber :
n countries:  2
n years:  20

Harvested irrigated temporary crop area: Groundnuts :
n countries:  23
n years:  22

Harvested irrigated temporary crop area: Sesame :
n countries:  16
n years:  27

Harvested irrigated permanent crop area: Olives :
n countries:  11
n years:  21

% of area equipped for irrigation by direct use of agricultural drainage water  :
n countries:  2
n years:  5

Harvested irrigated permanent crop area: Coconuts :
n countries:  4
n years:  17

Area equipped for irrigation by direct use of agricultural drainage water :
n countries:  2
n years:  5

Area equipped for irrigation by desalinated water :
n countries:  2
n years:  5

% of area equipped for irrigation by desalinated water :
n countries:  2
n years:  5

In [220]:
len(exclude_list)

24

In [221]:
df_short = df.query("Variable not in @exclude_list")

only consider data from 2001 until 2020

In [222]:
df_short = df_short.query("Year > 2000")

In [223]:
df_short.groupby(["Country","Variable","Year"]).count()

                                                                     Unit  \
Country     Variable                                           Year
Afghanistan % of agricultural GVA produced by irrigated agr... 2001     1
                                                               2002     1
                                                               2003     1
                                                               2004     1
                                                               2005     1
...                                                                   ...
Zimbabwe    Water withdrawal for cooling of thermoelectric ... 2016     1
                                                               2017     1
                                                               2018     1
                                                               2019     1
                                                               2020     1

                                                                     Value
Country     Variable                                           Year
Afghanistan % of agricultural GVA produced by irrigated agr... 2001      1
                                                               2002      1
                                                               2003      1
                                                               2004      1
                                                               2005      1
...                                                                    ...
Zimbabwe    Water withdrawal for cooling of thermoelectric ... 2016      1
                                                               2017      1
                                                               2018      1
                                                               2019      1
                                                               2020      1

[401568 rows x 2 columns]

filter for variables that have at least 3000 entries in the remaining data set

In [224]:
n_entry_dict = df_short.groupby("Variable").count().sort_values("Value")[["Value"]].to_dict()["Value"]
drop_list = [k for k,val in n_entry_dict.items() if val<3000]
print(len(n_entry_dict), len(drop_list))

169 90

In [225]:
df_shorter = df_short.query("Variable not in @drop_list")

In [226]:
df_shorter.set_index(["Country", "Year"])

                                                                                  Variable  \
Country                            Year
Samoa                              2020    Total area of the country (excl. coastal water)
                                   2020    Cultivated area (arable land + permanent crops)
                                   2020                                 Population density
                                   2020                   Agriculture, value added (% GDP)
                                   2020  Rural population with access to safe drinking-...
...                                                                                    ...
Bhutan                             2008                                GDP Deflator (2015)
Venezuela (Bolivarian Republic of) 2008                                GDP Deflator (2015)
Pakistan                           2008                                GDP Deflator (2015)
Latvia                             2008                                GDP Deflator (2015)
Solomon Islands                    2008                                GDP Deflator (2015)

                                              Unit       Value
Country                            Year
Samoa                              2020    1000 ha  279.000000
                                   2020    1000 ha   43.000000
                                   2020  inhab/km2   71.116129
                                   2020          %   10.543126
                                   2020          %   99.300000
...                                            ...         ...
Bhutan                             2008        NaN   95.752700
Venezuela (Bolivarian Republic of) 2008        NaN   87.838100
Pakistan                           2008        NaN   71.954400
Latvia                             2008        NaN  127.761100
Solomon Islands                    2008        NaN   79.955100

[286263 rows x 3 columns]

pivot

In [227]:
df_pivot = df_shorter.pivot_table(index=["Country","Year"], columns="Variable", values="Value")

In [228]:
df_pivot

Variable          % of agricultural GVA produced by irrigated agriculture  \
Country     Year
Afghanistan 2001                                          44.702708
            2002                                          44.684011
            2003                                          37.646401
            2004                                          53.059409
            2005                                          43.148507
...                                                             ...
Zimbabwe    2016                                           7.286943
            2017                                           7.193453
            2018                                           7.099892
            2019                                           7.099892
            2020                                           7.099892

Variable          % of agricultural water managed area equipped for irrigation  \
Country     Year
Afghanistan 2001                                         100.000000
            2002                                         100.000000
            2003                                         100.000000
            2004                                         100.000000
            2005                                         100.000000
...                                                             ...
Zimbabwe    2016                                          91.081382
            2017                                          91.296306
            2018                                          90.474331
            2019                                          90.474331
            2020                                          90.474331

Variable          % of area equipped for full control irrigation actually irrigated  \
Country     Year
Afghanistan 2001                                          66.760212
            2002                                          66.708229
            2003                                          54.675810
            2004                                          85.785536
            2005                                          65.024938
...                                                             ...
Zimbabwe    2016                                          82.107356
            2017                                          76.680282
            2018                                          68.542030
            2019                                          68.542030
            2020                                          68.542030

Variable          % of the cultivated area equipped for irrigation  \
Country     Year
Afghanistan 2001                                         41.364633
            2002                                         41.377531
            2003                                         40.556258
            2004                                         40.551131
            2005                                         40.556258
...                                                            ...
Zimbabwe    2016                                          3.985366
            2017                                          4.093415
            2018                                          4.408902
            2019                                          4.408902
            2020                                          4.408902

Variable          % of total country area cultivated  \
Country     Year
Afghanistan 2001                           11.875440
            2002                           11.875440
            2003                           12.115921
            2004                           12.117452
            2005                           12.115921
...                                              ...
Zimbabwe    2016                           10.492374
            2017                           10.492374
            2018                           10.492374
            2019                           10.492374
            2020                           10.492374

Variable          Agricultural water withdrawal  \
Country     Year
Afghanistan 2001                       20.00000
            2002                       20.00000
            2003                       20.00000
            2004                       20.00000
            2005                       20.00000
...                                         ...
Zimbabwe    2016                        2.72100
            2017                        2.77000
            2018                        3.04107
            2019                        3.04107
            2020                        3.04107

Variable          Agricultural water withdrawal as % of total renewable water resources  \
Country     Year
Afghanistan 2001                                          30.613807
            2002                                          30.613807
            2003                                          30.613807
            2004                                          30.613807
            2005                                          30.613807
...                                                             ...
Zimbabwe    2016                                          13.605000
            2017                                          13.850000
            2018                                          15.205348
            2019                                          15.205348
            2020                                          15.205348

Variable          Agricultural water withdrawal as % of total water withdrawal  \
Country     Year
Afghanistan 2001                                          98.518576
            2002                                          98.431107
            2003                                          98.343792
            2004                                          98.256633
            2005                                          98.169627
...                                                             ...
Zimbabwe    2016                                          79.989417
            2017                                          82.956485
            2018                                          80.635426
            2019                                          80.635426
            2020                                          80.635426

Variable          Agriculture, value added (% GDP)  \
Country     Year
Afghanistan 2001                         54.063068
            2002                         45.134344
            2003                         41.903476
            2004                         35.612891
            2005                         35.147545
...                                            ...
Zimbabwe    2016                          7.873986
            2017                          8.340969
            2018                          8.304691
            2019                          8.173215
            2020                          8.272958

Variable          Agriculture, value added to GDP  ...  \
Country     Year                                   ...
Afghanistan 2001                     1.945444e+09  ...
            2002                     1.869250e+09  ...
            2003                     1.981633e+09  ...
            2004                     1.918994e+09  ...
            2005                     2.186379e+09  ...
...                                           ...  ...
Zimbabwe    2016                     1.618000e+09  ...
            2017                     1.838425e+09  ...
            2018                     2.019000e+09  ...
            2019                     1.792801e+09  ...
            2020                     1.802408e+09  ...

Variable          Total population with access to safe drinking-water (JMP)  \
Country     Year
Afghanistan 2001                                               32.0
            2002                                               33.8
            2003                                               35.5
            2004                                               37.3
            2005                                               39.1
...                                                             ...
Zimbabwe    2016                                               76.9
            2017                                               76.9
            2018                                               76.9
            2019                                               76.9
            2020                                               76.9

Variable          Total renewable groundwater  Total renewable surface water  \
Country     Year
Afghanistan 2001                        10.65                          55.68
            2002                        10.65                          55.68
            2003                        10.65                          55.68
            2004                        10.65                          55.68
            2005                        10.65                          55.68
...                                       ...                            ...
Zimbabwe    2016                         6.00                          19.00
            2017                         6.00                          19.00
            2018                         6.00                          19.00
            2019                         6.00                          19.00
            2020                         6.00                          19.00

Variable          Total renewable water resources  \
Country     Year
Afghanistan 2001                            65.33
            2002                            65.33
            2003                            65.33
            2004                            65.33
            2005                            65.33
...                                           ...
Zimbabwe    2016                            20.00
            2017                            20.00
            2018                            20.00
            2019                            20.00
            2020                            20.00

Variable          Total renewable water resources per capita  \
Country     Year
Afghanistan 2001                                 3023.558860
            2002                                 2890.609479
            2003                                 2758.766770
            2004                                 2642.084964
            2005                                 2546.553933
...                                                      ...
Zimbabwe    2016                                 1425.483119
            2017                                 1404.830298
            2018                                 1385.156469
            2019                                 1365.610167
            2020                                 1345.630241

Variable          Total water withdrawal  Total water withdrawal per capita  \
Country     Year
Afghanistan 2001               20.300740                         939.545114
            2002               20.318780                         899.030431
            2003               20.336820                         858.786824
            2004               20.354860                         823.194085
            2005               20.372900                         794.132690
...                                  ...                                ...
Zimbabwe    2016                3.401700                         242.453296
            2017                3.339100                         234.543442
            2018                3.771382                         261.197685
            2019                3.771382                         257.511856
            2020                3.771382                         253.744260

Variable          Urban population  \
Country     Year
Afghanistan 2001          4648.139
            2002          4893.013
            2003          5155.788
            2004          5426.872
            2005          5691.836
...                            ...
Zimbabwe    2016          5215.894
            2017          5328.766
            2018          5447.513
            2019          5571.525
            2020          5700.460

Variable          Urban population with access to safe drinking-water (JMP)  \
Country     Year
Afghanistan 2001                                               54.1
            2002                                               55.9
            2003                                               57.8
            2004                                               59.6
            2005                                               61.5
...                                                             ...
Zimbabwe    2016                                               97.0
            2017                                               97.0
            2018                                               97.0
            2019                                               97.0
            2020                                               97.0

Variable          Water resources: total external renewable
Country     Year
Afghanistan 2001                                      18.18
            2002                                      18.18
            2003                                      18.18
            2004                                      18.18
            2005                                      18.18
...                                                     ...
Zimbabwe    2016                                       7.74
            2017                                       7.74
            2018                                       7.74
            2019                                       7.74
            2020                                       7.74

[3968 rows x 79 columns]

In [229]:
df_pivot.reset_index(inplace=True)

In [230]:
#fig, ax = plt.subplots(1,1,figsize=(20,500))
#sns.heatmap(df_pivot.isna(), ax=ax)

In [231]:
data_sparse_countries = ['Andorra','Antigua and Barbuda', 'Bahamas','Bosnia and Herzegovina','Brunei Darussalam','Cook Islands','Dominica','Equatorial Guinea','Faroe Islands','Grenada','Holy See','Kiribati', 'Liechtenstein','Marshall Islands','Micronesia (Federated States of)','Monaco','Montenegro','Nauru','Niue','Palau','Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines','Samoa','Serbia','San Marino', 'Sao Tome and Principe','Singapore', 'Seychelles','Solomon Islands','Tokelau','Tonga','Vanuatu','Djibouti','Maldives','Papua New Guinea','Tuvalu']

In [232]:
df_pivot_short = df_pivot.query("Country not in @data_sparse_countries")

In [233]:
df_pivot.Country.nunique()

200

In [234]:
df_pivot_short.Country.nunique()

163

In [235]:
for key, val in df_pivot_short.isna().sum().to_dict().items():
    print(key,'!',val)

Country ! 0
Year ! 0
% of agricultural GVA produced by irrigated agriculture ! 172
% of agricultural water managed area equipped for irrigation ! 40
% of area equipped for full control irrigation actually irrigated ! 326
% of the cultivated area equipped for irrigation ! 40
% of total country area cultivated ! 0
Agricultural water withdrawal ! 72
Agricultural water withdrawal as % of total renewable water resources ! 58
Agricultural water withdrawal as % of total water withdrawal ! 74
Agriculture, value added (% GDP) ! 0
Agriculture, value added to GDP ! 0
Arable land area ! 0
Area equipped for full control irrigation: actually irrigated ! 318
Area equipped for full control irrigation: total ! 40
Area equipped for irrigation: total ! 40
Cultivated area (arable land + permanent crops) ! 0
Dam capacity per capita ! 231
Dependency ratio ! 0
Environmental Flow Requirements ! 300
GDP Deflator (2015) ! 0
GDP per capita ! 0
Gross Domestic Product (GDP) ! 0
Groundwater produced internally ! 60
Groundwater: accounted inflow ! 0
Groundwater: accounted outflow to other countries ! 700
Groundwater: entering the country (total) ! 0
Groundwater: leaving the country to other countries (total) ! 700
Human Development Index (HDI) [highest = 1] ! 93
Industrial water withdrawal ! 38
Industrial water withdrawal as % of total water withdrawal ! 86
Industry, value added to GDP ! 0
Long-term average annual precipitation in depth ! 0
Long-term average annual precipitation in volume ! 0
MDG 7.5. Freshwater withdrawal as % of total renewable water resources ! 62
Municipal water withdrawal ! 7
Municipal water withdrawal as % of total withdrawal ! 75
National Rainfall Index (NRI) ! 198
Overlap between surface water and groundwater ! 60
Overlap: between surface water and groundwater ! 60
Permanent crops area ! 0
Population density ! 0
Ratio between rainfed and irrigated yields ! 140
Rural population ! 0
Rural population with access to safe drinking-water (JMP) ! 0
SDG 6.4.1. Industrial Water Use Efficiency ! 38
SDG 6.4.1. Irrigated Agriculture Water Use Efficiency ! 237
SDG 6.4.1. Services Water Use Efficiency ! 7
SDG 6.4.1. Water Use Efficiency ! 241
SDG 6.4.2. Water Stress ! 69
Services, value added to GDP ! 0
Surface water produced internally ! 40
Surface water: accounted flow of border rivers ! 0
Surface water: accounted inflow ! 0
Surface water: entering the country (total) ! 0
Surface water: inflow not submitted to treaties ! 0
Surface water: inflow secured through treaties ! 0
Surface water: inflow submitted to treaties ! 40
Surface water: leaving the country to other countries (total) ! 120
Surface water: outflow to other countries not submitted to treaties ! 180
Surface water: outflow to other countries secured through treaties ! 0
Surface water: outflow to other countries submitted to treaties ! 180
Surface water: total external renewable ! 0
Surface water: total flow of border rivers ! 100
Total agricultural water managed area ! 40
Total area of the country (excl. coastal water) ! 0
Total dam capacity ! 231
Total freshwater withdrawal ! 69
Total internal renewable water resources (IRWR) ! 0
Total internal renewable water resources per capita ! 0
Total population ! 0
Total population with access to safe drinking-water (JMP) ! 0
Total renewable groundwater ! 0
Total renewable surface water ! 0
Total renewable water resources ! 0
Total renewable water resources per capita ! 0
Total water withdrawal ! 69
Total water withdrawal per capita ! 69
Urban population ! 0
Urban population with access to safe drinking-water (JMP) ! 0
Water resources: total external renewable ! 0

In [236]:
for key, val in df_pivot_short.query("Year > 2010").isna().sum().to_dict().items():
    print(key,'!',val)

Country ! 0
Year ! 0
% of agricultural GVA produced by irrigated agriculture ! 4
% of agricultural water managed area equipped for irrigation ! 10
% of area equipped for full control irrigation actually irrigated ! 32
% of the cultivated area equipped for irrigation ! 10
% of total country area cultivated ! 0
Agricultural water withdrawal ! 1
Agricultural water withdrawal as % of total renewable water resources ! 1
Agricultural water withdrawal as % of total water withdrawal ! 1
Agriculture, value added (% GDP) ! 0
Agriculture, value added to GDP ! 0
Arable land area ! 0
Area equipped for full control irrigation: actually irrigated ! 26
Area equipped for full control irrigation: total ! 10
Area equipped for irrigation: total ! 10
Cultivated area (arable land + permanent crops) ! 0
Dam capacity per capita ! 119
Dependency ratio ! 0
Environmental Flow Requirements ! 150
GDP Deflator (2015) ! 0
GDP per capita ! 0
Gross Domestic Product (GDP) ! 0
Groundwater produced internally ! 30
Groundwater: accounted inflow ! 0
Groundwater: accounted outflow to other countries ! 350
Groundwater: entering the country (total) ! 0
Groundwater: leaving the country to other countries (total) ! 350
Human Development Index (HDI) [highest = 1] ! 30
Industrial water withdrawal ! 2
Industrial water withdrawal as % of total water withdrawal ! 2
Industry, value added to GDP ! 0
Long-term average annual precipitation in depth ! 0
Long-term average annual precipitation in volume ! 0
MDG 7.5. Freshwater withdrawal as % of total renewable water resources ! 1
Municipal water withdrawal ! 0
Municipal water withdrawal as % of total withdrawal ! 1
National Rainfall Index (NRI) ! 108
Overlap between surface water and groundwater ! 30
Overlap: between surface water and groundwater ! 30
Permanent crops area ! 0
Population density ! 0
Ratio between rainfed and irrigated yields ! 70
Rural population ! 0
Rural population with access to safe drinking-water (JMP) ! 0
SDG 6.4.1. Industrial Water Use Efficiency ! 2
SDG 6.4.1. Irrigated Agriculture Water Use Efficiency ! 5
SDG 6.4.1. Services Water Use Efficiency ! 0
SDG 6.4.1. Water Use Efficiency ! 6
SDG 6.4.2. Water Stress ! 1
Services, value added to GDP ! 0
Surface water produced internally ! 20
Surface water: accounted flow of border rivers ! 0
Surface water: accounted inflow ! 0
Surface water: entering the country (total) ! 0
Surface water: inflow not submitted to treaties ! 0
Surface water: inflow secured through treaties ! 0
Surface water: inflow submitted to treaties ! 20
Surface water: leaving the country to other countries (total) ! 60
Surface water: outflow to other countries not submitted to treaties ! 90
Surface water: outflow to other countries secured through treaties ! 0
Surface water: outflow to other countries submitted to treaties ! 90
Surface water: total external renewable ! 0
Surface water: total flow of border rivers ! 50
Total agricultural water managed area ! 10
Total area of the country (excl. coastal water) ! 0
Total dam capacity ! 119
Total freshwater withdrawal ! 1
Total internal renewable water resources (IRWR) ! 0
Total internal renewable water resources per capita ! 0
Total population ! 0
Total population with access to safe drinking-water (JMP) ! 0
Total renewable groundwater ! 0
Total renewable surface water ! 0
Total renewable water resources ! 0
Total renewable water resources per capita ! 0
Total water withdrawal ! 1
Total water withdrawal per capita ! 1
Urban population ! 0
Urban population with access to safe drinking-water (JMP) ! 0
Water resources: total external renewable ! 0

exclude repeating information and further sparse variables

In [237]:
dropdrop_list = ["GDP Deflator (2015)" , "Environmental Flow Requirements" , "Groundwater: accounted outflow to other countries" , "Groundwater: leaving the country to other countries (total)"]

In [238]:
df_pivot_shorter = df_pivot_short.drop(columns=dropdrop_list)

In [239]:
print(df_pivot_shorter.columns)

Index(['Country', 'Year',
       '% of agricultural GVA produced by irrigated agriculture',
       '% of agricultural water managed area equipped for irrigation',
       '% of area equipped for full control irrigation actually irrigated',
       '% of the cultivated area equipped for irrigation',
       '% of total country area cultivated', 'Agricultural water withdrawal',
       'Agricultural water withdrawal as % of total renewable water resources',
       'Agricultural water withdrawal as % of total water withdrawal',
       'Agriculture, value added (% GDP)', 'Agriculture, value added to GDP',
       'Arable land area',
       'Area equipped for full control irrigation: actually irrigated',
       'Area equipped for full control irrigation: total',
       'Area equipped for irrigation: total',
       'Cultivated area (arable land + permanent crops)',
       'Dam capacity per capita', 'Dependency ratio', 'GDP per capita',
       'Gross Domestic Product (GDP)', 'Groundwater produced internally',
       'Groundwater: accounted inflow',
       'Groundwater: entering the country (total)',
       'Human Development Index (HDI) [highest = 1]',
       'Industrial water withdrawal',
       'Industrial water withdrawal as % of total water withdrawal',
       'Industry, value added to GDP',
       'Long-term average annual precipitation in depth',
       'Long-term average annual precipitation in volume',
       'MDG 7.5. Freshwater withdrawal as % of total renewable water resources',
       'Municipal water withdrawal',
       'Municipal water withdrawal as % of total withdrawal',
       'National Rainfall Index (NRI)',
       'Overlap between surface water and groundwater',
       'Overlap: between surface water and groundwater',
       'Permanent crops area', 'Population density',
       'Ratio between rainfed and irrigated yields', 'Rural population',
       'Rural population with access to safe drinking-water (JMP)',
       'SDG 6.4.1. Industrial Water Use Efficiency',
       'SDG 6.4.1. Irrigated Agriculture Water Use Efficiency',
       'SDG 6.4.1. Services Water Use Efficiency',
       'SDG 6.4.1. Water Use Efficiency', 'SDG 6.4.2. Water Stress',
       'Services, value added to GDP', 'Surface water produced internally',
       'Surface water: accounted flow of border rivers',
       'Surface water: accounted inflow',
       'Surface water: entering the country (total)',
       'Surface water: inflow not submitted to treaties',
       'Surface water: inflow secured through treaties',
       'Surface water: inflow submitted to treaties',
       'Surface water: leaving the country to other countries (total)',
       'Surface water: outflow to other countries not submitted to treaties',
       'Surface water: outflow to other countries secured through treaties',
       'Surface water: outflow to other countries submitted to treaties',
       'Surface water: total external renewable',
       'Surface water: total flow of border rivers',
       'Total agricultural water managed area',
       'Total area of the country (excl. coastal water)', 'Total dam capacity',
       'Total freshwater withdrawal',
       'Total internal renewable water resources (IRWR)',
       'Total internal renewable water resources per capita',
       'Total population',
       'Total population with access to safe drinking-water (JMP)',
       'Total renewable groundwater', 'Total renewable surface water',
       'Total renewable water resources',
       'Total renewable water resources per capita', 'Total water withdrawal',
       'Total water withdrawal per capita', 'Urban population',
       'Urban population with access to safe drinking-water (JMP)',
       'Water resources: total external renewable'],
      dtype='object', name='Variable')

In [240]:
df_pivot_shorter.shape

(3238, 77)

In [241]:
# start1 = 68
# start2 = 2

# limits1 = (start1, start1+6)
# limits2 = (start2, start2+75)

# vars1 = df_pivot_shorter.columns[limits1[0]:limits1[1]]
# vars2 = df_pivot_shorter.columns[limits2[0]:limits2[1]]

# print(vars1)
# print(vars2)

In [242]:
# fig, axs = plt.subplots(75,6, figsize=(30,400))

# for i, v1 in enumerate(vars1):
#     for j, v2 in enumerate(vars2):
#         sns.scatterplot(x=df_pivot_shorter[v2], y=df_pivot_shorter[v1], ax=axs[j,i])

# fig.tight_layout()

drop linear dependent variables

In [243]:
linear_drop_list = ["% of the cultivated area equipped for irrigation", "Area equipped for full control irrigation: actually irrigated", "Area equipped for full control irrigation: total", "MDG 7.5. Freshwater withdrawal as % of total renewable water resources", "Arable land area", "Area equipped for irrigation: total", "Long-term average annual precipitation in volume", "Long-term average annual precipitation in depth", "Groundwater produced internally","Surface water produced internally", "Permanent crops area", "Overlap between surface water and groundwater", "Overlap: between surface water and groundwater", "Rural population with access to safe drinking-water (JMP)", "Surface water: inflow not submitted to treaties", "Surface water: inflow submitted to treaties", "Surface water: accounted inflow", "Total renewable water resources", "Surface water: outflow to other countries secured through treaties", "Surface water: total external renewable", "Surface water: total flow of border rivers", "Surface water: accounted flow of border rivers", "Total renewable surface water", "% of area equipped for full control irrigation actually irrigated", "Surface water: outflow to other countries not submitted to treaties", "Surface water: outflow to other countries submitted to treaties", "Surface water: inflow secured through treaties", "Total freshwater withdrawal"]
drop_for_now_list = ["Human Development Index (HDI) [highest = 1]", "Industry, value added to GDP" , "Services, value added to GDP", "Agriculture, value added to GDP", "Industrial water withdrawal as % of total water withdrawal", "Municipal water withdrawal as % of total withdrawal"]

In [244]:
df_indy = df_pivot_shorter.drop(columns=linear_drop_list)
df_indy = df_indy.drop(columns=drop_for_now_list)

In [245]:
df_indy.shape

(3238, 43)

In [246]:
df_indy.head(3)

Variable,Country,Year,% of agricultural GVA produced by irrigated agriculture,% of agricultural water managed area equipped for irrigation,% of total country area cultivated,Agricultural water withdrawal,Agricultural water withdrawal as % of total renewable water resources,Agricultural water withdrawal as % of total water withdrawal,"Agriculture, value added (% GDP)",Cultivated area (arable land + permanent crops),...,Total internal renewable water resources per capita,Total population,Total population with access to safe drinking-water (JMP),Total renewable groundwater,Total renewable water resources per capita,Total water withdrawal,Total water withdrawal per capita,Urban population,Urban population with access to safe drinking-water (JMP),Water resources: total external renewable
0,Afghanistan,2001,44.702708,100.0,11.875440,20.0,30.613807,98.518576,54.063068,7753.0,...,2182.164400,21606.988,32.0,10.65,3023.558860,20.30074,939.545114,4648.139,54.1,18.18
1,Afghanistan,2002,44.684011,100.0,11.875440,20.0,30.613807,98.431107,45.134344,7753.0,...,2086.212107,22600.770,33.8,10.65,2890.609479,20.31878,899.030431,4893.013,55.9,18.18
2,Afghanistan,2003,37.646401,100.0,12.115921,20.0,30.613807,98.343792,41.903476,7910.0,...,1991.058521,23680.871,35.5,10.65,2758.766770,20.33682,858.786824,5155.788,57.8,18.18

improve names

In [247]:
df_indy.columns = df_indy.columns.str.replace(" ","_")

In [248]:
df_indy.head(3)

Variable,Country,Year,%_of_agricultural_GVA_produced_by_irrigated_agriculture,%_of_agricultural_water_managed_area_equipped_for_irrigation,%_of_total_country_area_cultivated,Agricultural_water_withdrawal,Agricultural_water_withdrawal_as_%_of_total_renewable_water_resources,Agricultural_water_withdrawal_as_%_of_total_water_withdrawal,"Agriculture,_value_added_(%_GDP)",Cultivated_area_(arable_land_+_permanent_crops),...,Total_internal_renewable_water_resources_per_capita,Total_population,Total_population_with_access_to_safe_drinking-water_(JMP),Total_renewable_groundwater,Total_renewable_water_resources_per_capita,Total_water_withdrawal,Total_water_withdrawal_per_capita,Urban_population,Urban_population_with_access_to_safe_drinking-water_(JMP),Water_resources:_total_external_renewable
0,Afghanistan,2001,44.702708,100.0,11.875440,20.0,30.613807,98.518576,54.063068,7753.0,...,2182.164400,21606.988,32.0,10.65,3023.558860,20.30074,939.545114,4648.139,54.1,18.18
1,Afghanistan,2002,44.684011,100.0,11.875440,20.0,30.613807,98.431107,45.134344,7753.0,...,2086.212107,22600.770,33.8,10.65,2890.609479,20.31878,899.030431,4893.013,55.9,18.18
2,Afghanistan,2003,37.646401,100.0,12.115921,20.0,30.613807,98.343792,41.903476,7910.0,...,1991.058521,23680.871,35.5,10.65,2758.766770,20.33682,858.786824,5155.788,57.8,18.18

In [249]:
for col in df_indy.columns.sort_values():
    print(col)

%_of_agricultural_GVA_produced_by_irrigated_agriculture
%_of_agricultural_water_managed_area_equipped_for_irrigation
%_of_total_country_area_cultivated
Agricultural_water_withdrawal
Agricultural_water_withdrawal_as_%_of_total_renewable_water_resources
Agricultural_water_withdrawal_as_%_of_total_water_withdrawal
Agriculture,_value_added_(%_GDP)
Country
Cultivated_area_(arable_land_+_permanent_crops)
Dam_capacity_per_capita
Dependency_ratio
GDP_per_capita
Gross_Domestic_Product_(GDP)
Groundwater:_accounted_inflow
Groundwater:_entering_the_country_(total)
Industrial_water_withdrawal
Municipal_water_withdrawal
National_Rainfall_Index_(NRI)
Population_density
Ratio_between_rainfed_and_irrigated_yields
Rural_population
SDG_6.4.1._Industrial_Water_Use_Efficiency
SDG_6.4.1._Irrigated_Agriculture_Water_Use_Efficiency
SDG_6.4.1._Services_Water_Use_Efficiency
SDG_6.4.1._Water_Use_Efficiency
SDG_6.4.2._Water_Stress
Surface_water:_entering_the_country_(total)
Surface_water:_leaving_the_country_to_other_countries_(total)
Total_agricultural_water_managed_area
Total_area_of_the_country_(excl._coastal_water)
Total_dam_capacity
Total_internal_renewable_water_resources_(IRWR)
Total_internal_renewable_water_resources_per_capita
Total_population
Total_population_with_access_to_safe_drinking-water_(JMP)
Total_renewable_groundwater
Total_renewable_water_resources_per_capita
Total_water_withdrawal
Total_water_withdrawal_per_capita
Urban_population
Urban_population_with_access_to_safe_drinking-water_(JMP)
Water_resources:_total_external_renewable
Year

In [250]:
colnames = []
for col in df_indy.columns:
    col = col.replace("_(NRI)","")
    col = col.replace("_(GDP)","")
    col = col.replace("_(JMP)","")
    col = col.replace("_(IRWR)","")
    col = col.replace("SDG_6.4.1._","")
    col = col.replace("SDG_6.4.2._","")
    col = col.replace("-","_")
    col = col.replace(":","")
    col = col.replace(".","")
    col = col.replace(",","")
    col = col.replace("(","")
    col = col.replace(")","")
    col = col.lower()
    col = col.replace("+","plus")
    colnames.append(col)
colnames

['country',
 'year',
 '%_of_agricultural_gva_produced_by_irrigated_agriculture',
 '%_of_agricultural_water_managed_area_equipped_for_irrigation',
 '%_of_total_country_area_cultivated',
 'agricultural_water_withdrawal',
 'agricultural_water_withdrawal_as_%_of_total_renewable_water_resources',
 'agricultural_water_withdrawal_as_%_of_total_water_withdrawal',
 'agriculture_value_added_%_gdp',
 'cultivated_area_arable_land_plus_permanent_crops',
 'dam_capacity_per_capita',
 'dependency_ratio',
 'gdp_per_capita',
 'gross_domestic_product',
 'groundwater_accounted_inflow',
 'groundwater_entering_the_country_total',
 'industrial_water_withdrawal',
 'municipal_water_withdrawal',
 'national_rainfall_index',
 'population_density',
 'ratio_between_rainfed_and_irrigated_yields',
 'rural_population',
 'industrial_water_use_efficiency',
 'irrigated_agriculture_water_use_efficiency',
 'services_water_use_efficiency',
 'water_use_efficiency',
 'water_stress',
 'surface_water_entering_the_country_total',
 'surface_water_leaving_the_country_to_other_countries_total',
 'total_agricultural_water_managed_area',
 'total_area_of_the_country_excl_coastal_water',
 'total_dam_capacity',
 'total_internal_renewable_water_resources',
 'total_internal_renewable_water_resources_per_capita',
 'total_population',
 'total_population_with_access_to_safe_drinking_water',
 'total_renewable_groundwater',
 'total_renewable_water_resources_per_capita',
 'total_water_withdrawal',
 'total_water_withdrawal_per_capita',
 'urban_population',
 'urban_population_with_access_to_safe_drinking_water',
 'water_resources_total_external_renewable']

In [251]:
df_indy.columns = colnames

In [252]:
df_indy.total_dam_capacity.describe()

count    3007.000000
mean       45.885684
std       137.960847
min         0.000000
25%         0.333706
50%         5.271500
75%        23.260368
max       841.505700
Name: total_dam_capacity, dtype: float64

dependent dropping

In [253]:
df_indy = df_indy.drop(columns=["gross_domestic_product", "urban_population_with_access_to_safe_drinking_water"])

plot nan maps

In [255]:
# plt.close("all")
# for i, c in enumerate(df_indy.country.unique()):
#     fig, ax = plt.subplots(1,1, figsize=(10,4))
#     sns.heatmap(df_indy.query("country == @c").isna(), ax=ax)
#     ax.set_title(c)
#     #if i==1:    break
#     fig.savefig("images/"+c+"_nan_heatmap.png")

#### train test validation split

In [112]:
from sklearn.model_selection import train_test_split
RSEED = 5

In [113]:
targets = ['gdp_per_capita', 'water_stress', 'total_population_with_access_to_safe_drinking_water']

Y = df_indy[targets]
X = df_indy.drop(columns=targets)

X_train, X_pretest, Y_train, Y_pretest = train_test_split(X, Y, test_size=0.30, random_state=RSEED, stratify=X.country)
X_test, X_valid, Y_test, Y_valid = train_test_split(X_pretest, Y_pretest, test_size=0.50, random_state=RSEED, stratify=X_pretest.country)

In [114]:
Y_test.shape

(486, 3)

imputation

In [259]:
#Qatar:
index_list = X_train.query("country == 'Qatar'").index
X_train.loc[index_list,'dam_capacity_per_capita'] = 0
X_train.loc[index_list,'total_dam_capacity'] = 0
X_train.loc[index_list,'ratio_between_rainfed_and_irrigated_yields'] = 0

#Republic of Korea:
index_list = X_train.query("country == 'Republic of Korea'").index
X_train.loc[index_list,'national_rainfall_index'] = 1150

#Saudi Arabia:
index_list = X_train.query("country == 'Saudi Arabia'").index
X_train.loc[index_list,'ratio_between_rainfed_and_irrigated_yields'] = 0
X_train.loc[index_list,'surface_water_leaving_the_country_to_other_countries_total'] = 0

#South Sudan:
index_list = X_train.query("country == 'South Sudan'").index
X_train.loc[index_list,'national_rainfall_index'] = 0
X_train.loc[index_list,'total_dam_capacity'] = 0
X_train.loc[index_list,'dam_capacity_per_capita'] = 0

#Sudan:
index_list = X_train.query("country == 'Sudan'").index
X_train.loc[index_list,'national_rainfall_index'] = 257

#Timor-Leste:
index_list = X_train.query("country == 'Timor-Leste'").index
X_train.loc[index_list,'national_rainfall_index'] = 1500
X_train.loc[index_list,'total_dam_capacity'] = 0
X_train.loc[index_list,'dam_capacity_per_capita'] = 0

#Turkmenistan:
index_list = X_train.query("country == 'Turkmenistan'").index
X_train.loc[index_list,'ratio_between_rainfed_and_irrigated_yields'] = 0

#United Arab Emirates:
index_list = X_train.query("country == 'United Arab Emirates'").index
X_train.loc[index_list,'ratio_between_rainfed_and_irrigated_yields'] = 0

#Yemen:
index_list = X_train.query("country == 'Yemen'").index
X_train.loc[index_list,'surface_water_leaving_the_country_to_other_countries_total'] = 0
#Iceland#
index_list = X_train.query("country == 'Iceland'").index
X_train.loc[index_list,'%_of_agricultural_water_managed_area_equipped_for_irrigation'] = 0
X_train.loc[index_list,'total_agricultural_water_managed_area'] = 0
#Iraq#
index_list = X_train.query("country == 'Iraq'").index
X_train.loc[index_list,'surface_water_leaving_the_country_to_other_countries_total'] = 0
#Israel#
index_list = X_train.query("country == 'Israel'").index
X_train.loc[index_list,'dam_capacity_per_capita'] = 0
X_train.loc[index_list,'total_dam_capacity'] = 0
#Jordan#
index_list = X_train.query("country == 'Jordan'").index
X_train.loc[index_list,'surface_water_leaving_the_country_to_other_countries_total'] = 0
#Kuwait#
index_list = X_train.query("country == 'Kuwait'").index
X_train.loc[index_list,'dam_capacity_per_capita'] = 0
X_train.loc[index_list,'total_dam_capacity'] = 0
X_train.loc[index_list,'ratio_between_rainfed_and_irrigated_yields'] = 1.24
#Luxembourg#
index_list = X_train.query("country == 'Luxembourg'").index
X_train.loc[index_list,'national_rainfall_index'] = 847.9
#Mauritius#
index_list = X_train.query("country == 'Mauritius'").index
X_train.loc[index_list,'national_rainfall_index'] = 2342
#Oman#
index_list = X_train.query("country == 'Oman'").index
X_train.loc[index_list,'ratio_between_rainfed_and_irrigated_yields'] = 1.24
X_train.loc[index_list,'surface_water_leaving_the_country_to_other_countries_total'] = 0
#Palestine#
index_list = X_train.query("country == 'Palestine'").index
X_train.loc[index_list,'national_rainfall_index'] = 490
#Azerbaijan
index_aze = X_train.query("country == 'Azerbaijan'").index
X_train.loc[index_list,'surface_water_leaving_the_country_to_other_countries_total'] = 0
#Bahrain
index_bah = X_train.query("country == 'Bahrain'").index
X_train.loc[index_bah,'national_rainfall_index'] = 36
#Barbados
index_bar = X_train.query("country == 'Barbados'").index
X_train.loc[index_bar,'dam_capacity_per_capita'] = 0
X_train.loc[index_bar,'total_dam_capacity'] = 0
X_train.loc[index_bar,'national_rainfall_index'] = 1525
#Burundi
index_bur = X_train.query("country == 'Burundi'").index
X_train.loc[index_bur,'dam_capacity_per_capita'] = 0
X_train.loc[index_bur,'total_dam_capacity'] = 0
#Central African Republic
index_car = X_train.query("country == 'Central African Republic'").index
X_train.loc[index_car,'dam_capacity_per_capita'] = 0
X_train.loc[index_car,'total_dam_capacity'] = 0
#Chad
index_cha = X_train.query("country == 'Chad'").index
X_train.loc[index_cha,'dam_capacity_per_capita'] = 0
X_train.loc[index_cha,'total_dam_capacity'] = 0
#Comoros
index_com = X_train.query("country == 'Comoros'").index
X_train.loc[index_com,'dam_capacity_per_capita'] = 0
X_train.loc[index_com,'total_dam_capacity'] = 0
#Democratic People's Republic of Korea
index_dpr = X_train.query("country == \"Democratic People's Republic of Korea\"").index
X_train.loc[index_dpr, 'national_rainfall_index'] = 244
#Egypt
index_egy = X_train.query("country == 'Egypt'").index
X_train.loc[index_egy, 'ratio_between_rainfed_and_irrigated_yields'] = 1.124
#Gambia
index_gam = X_train.query("country == 'Gambia'").index
X_train.loc[index_gam,'dam_capacity_per_capita'] = 0
X_train.loc[index_gam,'total_dam_capacity'] = 0

In [260]:
#Qatar:
index_list = X_valid.query("country == 'Qatar'").index
X_valid.loc[index_list,'dam_capacity_per_capita'] = 0
X_valid.loc[index_list,'total_dam_capacity'] = 0
X_valid.loc[index_list,'ratio_between_rainfed_and_irrigated_yields'] = 0

#Republic of Korea:
index_list = X_valid.query("country == 'Republic of Korea'").index
X_valid.loc[index_list,'national_rainfall_index'] = 1150

#Saudi Arabia:
index_list = X_valid.query("country == 'Saudi Arabia'").index
X_valid.loc[index_list,'ratio_between_rainfed_and_irrigated_yields'] = 0
X_valid.loc[index_list,'surface_water_leaving_the_country_to_other_countries_total'] = 0

#South Sudan:
index_list = X_valid.query("country == 'South Sudan'").index
X_valid.loc[index_list,'national_rainfall_index'] = 0
X_valid.loc[index_list,'total_dam_capacity'] = 0
X_valid.loc[index_list,'dam_capacity_per_capita'] = 0

#Sudan:
index_list = X_valid.query("country == 'Sudan'").index
X_valid.loc[index_list,'national_rainfall_index'] = 257

#Timor-Leste:
index_list = X_valid.query("country == 'Timor-Leste'").index
X_valid.loc[index_list,'national_rainfall_index'] = 1500
X_valid.loc[index_list,'total_dam_capacity'] = 0
X_valid.loc[index_list,'dam_capacity_per_capita'] = 0

#Turkmenistan:
index_list = X_valid.query("country == 'Turkmenistan'").index
X_valid.loc[index_list,'ratio_between_rainfed_and_irrigated_yields'] = 0

#United Arab Emirates:
index_list = X_valid.query("country == 'United Arab Emirates'").index
X_valid.loc[index_list,'ratio_between_rainfed_and_irrigated_yields'] = 0

#Yemen:
index_list = X_valid.query("country == 'Yemen'").index
X_valid.loc[index_list,'surface_water_leaving_the_country_to_other_countries_total'] = 0
#Iceland#
index_list = X_valid.query("country == 'Iceland'").index
X_valid.loc[index_list,'%_of_agricultural_water_managed_area_equipped_for_irrigation'] = 0
X_valid.loc[index_list,'total_agricultural_water_managed_area'] = 0
#Iraq#
index_list = X_valid.query("country == 'Iraq'").index
X_valid.loc[index_list,'surface_water_leaving_the_country_to_other_countries_total'] = 0
#Israel#
index_list = X_valid.query("country == 'Israel'").index
X_valid.loc[index_list,'dam_capacity_per_capita'] = 0
X_valid.loc[index_list,'total_dam_capacity'] = 0
#Jordan#
index_list = X_valid.query("country == 'Jordan'").index
X_valid.loc[index_list,'surface_water_leaving_the_country_to_other_countries_total'] = 0
#Kuwait#
index_list = X_valid.query("country == 'Kuwait'").index
X_valid.loc[index_list,'dam_capacity_per_capita'] = 0
X_valid.loc[index_list,'total_dam_capacity'] = 0
X_valid.loc[index_list,'ratio_between_rainfed_and_irrigated_yields'] = 1.24
#Luxembourg#
index_list = X_valid.query("country == 'Luxembourg'").index
X_valid.loc[index_list,'national_rainfall_index'] = 847.9
#Mauritius#
index_list = X_valid.query("country == 'Mauritius'").index
X_valid.loc[index_list,'national_rainfall_index'] = 2342
#Oman#
index_list = X_valid.query("country == 'Oman'").index
X_valid.loc[index_list,'ratio_between_rainfed_and_irrigated_yields'] = 1.24
X_valid.loc[index_list,'surface_water_leaving_the_country_to_other_countries_total'] = 0
#Palestine#
index_list = X_valid.query("country == 'Palestine'").index
X_valid.loc[index_list,'national_rainfall_index'] = 490
#Azerbaijan
index_aze = X_valid.query("country == 'Azerbaijan'").index
X_valid.loc[index_list,'surface_water_leaving_the_country_to_other_countries_total'] = 0
#Bahrain
index_bah = X_valid.query("country == 'Bahrain'").index
X_valid.loc[index_bah,'national_rainfall_index'] = 36
#Barbados
index_bar = X_valid.query("country == 'Barbados'").index
X_valid.loc[index_bar,'dam_capacity_per_capita'] = 0
X_valid.loc[index_bar,'total_dam_capacity'] = 0
X_valid.loc[index_bar,'national_rainfall_index'] = 1525
#Burundi
index_bur = X_valid.query("country == 'Burundi'").index
X_valid.loc[index_bur,'dam_capacity_per_capita'] = 0
X_valid.loc[index_bur,'total_dam_capacity'] = 0
#Central African Republic
index_car = X_valid.query("country == 'Central African Republic'").index
X_valid.loc[index_car,'dam_capacity_per_capita'] = 0
X_valid.loc[index_car,'total_dam_capacity'] = 0
#Chad
index_cha = X_valid.query("country == 'Chad'").index
X_valid.loc[index_cha,'dam_capacity_per_capita'] = 0
X_valid.loc[index_cha,'total_dam_capacity'] = 0
#Comoros
index_com = X_valid.query("country == 'Comoros'").index
X_valid.loc[index_com,'dam_capacity_per_capita'] = 0
X_valid.loc[index_com,'total_dam_capacity'] = 0
#Democratic People's Republic of Korea
index_dpr = X_valid.query("country == \"Democratic People's Republic of Korea\"").index
X_valid.loc[index_dpr, 'national_rainfall_index'] = 244
#Egypt
index_egy = X_valid.query("country == 'Egypt'").index
X_valid.loc[index_egy, 'ratio_between_rainfed_and_irrigated_yields'] = 1.124
#Gambia
index_gam = X_valid.query("country == 'Gambia'").index
X_valid.loc[index_gam,'dam_capacity_per_capita'] = 0
X_valid.loc[index_gam,'total_dam_capacity'] = 0

In [261]:
X_train.isna().sum()

country                                                                    0
year                                                                       0
%_of_agricultural_gva_produced_by_irrigated_agriculture                  127
%_of_agricultural_water_managed_area_equipped_for_irrigation              16
%_of_total_country_area_cultivated                                         0
agricultural_water_withdrawal                                             52
agricultural_water_withdrawal_as_%_of_total_renewable_water_resources     39
agricultural_water_withdrawal_as_%_of_total_water_withdrawal              54
agriculture_value_added_%_gdp                                              0
cultivated_area_arable_land_plus_permanent_crops                           0
dam_capacity_per_capita                                                   16
dependency_ratio                                                           0
gross_domestic_product                                                     0
groundwater_accounted_inflow                                               0
groundwater_entering_the_country_total                                     0
industrial_water_withdrawal                                               29
municipal_water_withdrawal                                                 5
national_rainfall_index                                                   14
population_density                                                         0
ratio_between_rainfed_and_irrigated_yields                                 0
rural_population                                                           0
industrial_water_use_efficiency                                           29
irrigated_agriculture_water_use_efficiency                               172
services_water_use_efficiency                                              5
water_use_efficiency                                                     175
surface_water_entering_the_country_total                                   0
surface_water_leaving_the_country_to_other_countries_total                14
total_agricultural_water_managed_area                                     16
total_area_of_the_country_excl_coastal_water                               0
total_dam_capacity                                                        16
total_internal_renewable_water_resources                                   0
total_internal_renewable_water_resources_per_capita                        0
total_population                                                           0
total_renewable_groundwater                                                0
total_renewable_water_resources_per_capita                                 0
total_water_withdrawal                                                    49
total_water_withdrawal_per_capita                                         49
urban_population                                                           0
urban_population_with_access_to_safe_drinking_water                        0
water_resources_total_external_renewable                                   0
dtype: int64

In [296]:
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

In [264]:
le = LabelEncoder()
X_train['country'] = le.fit_transform(X_train['country'])

In [266]:
X_train.country.unique()

array([ 41,  56,   7,  79,  39,  75,  89,  73,  43, 119,  66,  62,  45,
        61,  60,  42, 121, 155,   4,  78, 101, 149,  21, 126,  29,  77,
        50, 114, 160,  57,   1,  68, 115,  10,  47,  22,  38,   6, 137,
       105,  85,  54, 159,  33, 107,  40, 110, 113, 117,  35,  19,  46,
        20, 140, 125,   2,  44, 129, 139, 162, 147,  95, 141,  31,  13,
       157,  15,   0,  92,  67, 124, 100,  48,  90,  14,  27,  72, 153,
       131,   5, 103, 123, 142,  32, 134, 128,  16,  96,  83, 102,  24,
        74,  81,  55,  37,  64,  28,  80,  87, 154, 156, 138,  11,  97,
        17, 158,  49,  99, 135, 161, 127, 104,  51,  93,  59, 151,  26,
        23,  52,  30, 144, 122, 136, 148,  91, 150,   8,  82, 133,  65,
        12, 132,  88,  36, 146,  86,   3, 118,   9, 111, 130,  25,  53,
       145, 152,  94,  76,  18, 116, 106,  58, 143, 112, 109,  70,  63,
       120,  98,  84, 108,  69,  34,  71])

In [279]:
country_ids = {c: float(i) for i, c in enumerate(le.classes_)}
country_ids

{'Afghanistan': 0.0,
 'Albania': 1.0,
 'Algeria': 2.0,
 'Angola': 3.0,
 'Argentina': 4.0,
 'Armenia': 5.0,
 'Australia': 6.0,
 'Austria': 7.0,
 'Azerbaijan': 8.0,
 'Bahrain': 9.0,
 'Bangladesh': 10.0,
 'Barbados': 11.0,
 'Belarus': 12.0,
 'Belgium': 13.0,
 'Belize': 14.0,
 'Benin': 15.0,
 'Bhutan': 16.0,
 'Bolivia (Plurinational State of)': 17.0,
 'Botswana': 18.0,
 'Brazil': 19.0,
 'Bulgaria': 20.0,
 'Burkina Faso': 21.0,
 'Burundi': 22.0,
 'Cabo Verde': 23.0,
 'Cambodia': 24.0,
 'Cameroon': 25.0,
 'Canada': 26.0,
 'Central African Republic': 27.0,
 'Chad': 28.0,
 'Chile': 29.0,
 'China': 30.0,
 'Colombia': 31.0,
 'Comoros': 32.0,
 'Congo': 33.0,
 'Costa Rica': 34.0,
 'Croatia': 35.0,
 'Cuba': 36.0,
 'Cyprus': 37.0,
 'Czechia': 38.0,
 "Côte d'Ivoire": 39.0,
 "Democratic People's Republic of Korea": 40.0,
 'Democratic Republic of the Congo': 41.0,
 'Denmark': 42.0,
 'Dominican Republic': 43.0,
 'Ecuador': 44.0,
 'Egypt': 45.0,
 'El Salvador': 46.0,
 'Eritrea': 47.0,
 'Estonia': 48.0,
 'Eswatini': 49.0,
 'Ethiopia': 50.0,
 'Fiji': 51.0,
 'Finland': 52.0,
 'France': 53.0,
 'Gabon': 54.0,
 'Gambia': 55.0,
 'Georgia': 56.0,
 'Germany': 57.0,
 'Ghana': 58.0,
 'Greece': 59.0,
 'Guatemala': 60.0,
 'Guinea': 61.0,
 'Guinea-Bissau': 62.0,
 'Guyana': 63.0,
 'Haiti': 64.0,
 'Honduras': 65.0,
 'Hungary': 66.0,
 'Iceland': 67.0,
 'India': 68.0,
 'Indonesia': 69.0,
 'Iran (Islamic Republic of)': 70.0,
 'Iraq': 71.0,
 'Ireland': 72.0,
 'Israel': 73.0,
 'Italy': 74.0,
 'Jamaica': 75.0,
 'Japan': 76.0,
 'Jordan': 77.0,
 'Kazakhstan': 78.0,
 'Kenya': 79.0,
 'Kuwait': 80.0,
 'Kyrgyzstan': 81.0,
 "Lao People's Democratic Republic": 82.0,
 'Latvia': 83.0,
 'Lebanon': 84.0,
 'Lesotho': 85.0,
 'Liberia': 86.0,
 'Libya': 87.0,
 'Lithuania': 88.0,
 'Luxembourg': 89.0,
 'Madagascar': 90.0,
 'Malawi': 91.0,
 'Malaysia': 92.0,
 'Mali': 93.0,
 'Malta': 94.0,
 'Mauritania': 95.0,
 'Mauritius': 96.0,
 'Mexico': 97.0,
 'Mongolia': 98.0,
 'Morocco': 99.0,
 'Mozambique': 100.0,
 'Myanmar': 101.0,
 'Namibia': 102.0,
 'Nepal': 103.0,
 'Netherlands (Kingdom of the)': 104.0,
 'New Zealand': 105.0,
 'Nicaragua': 106.0,
 'Niger': 107.0,
 'Nigeria': 108.0,
 'North Macedonia': 109.0,
 'Norway': 110.0,
 'Oman': 111.0,
 'Pakistan': 112.0,
 'Palestine': 113.0,
 'Panama': 114.0,
 'Paraguay': 115.0,
 'Peru': 116.0,
 'Philippines': 117.0,
 'Poland': 118.0,
 'Portugal': 119.0,
 'Puerto Rico': 120.0,
 'Qatar': 121.0,
 'Republic of Korea': 122.0,
 'Republic of Moldova': 123.0,
 'Romania': 124.0,
 'Russian Federation': 125.0,
 'Rwanda': 126.0,
 'Saudi Arabia': 127.0,
 'Senegal': 128.0,
 'Sierra Leone': 129.0,
 'Slovakia': 130.0,
 'Slovenia': 131.0,
 'Somalia': 132.0,
 'South Africa': 133.0,
 'South Sudan': 134.0,
 'Spain': 135.0,
 'Sri Lanka': 136.0,
 'Sudan': 137.0,
 'Suriname': 138.0,
 'Sweden': 139.0,
 'Switzerland': 140.0,
 'Syrian Arab Republic': 141.0,
 'Tajikistan': 142.0,
 'Thailand': 143.0,
 'Timor-Leste': 144.0,
 'Togo': 145.0,
 'Trinidad and Tobago': 146.0,
 'Tunisia': 147.0,
 'Turkmenistan': 148.0,
 'Türkiye': 149.0,
 'Uganda': 150.0,
 'Ukraine': 151.0,
 'United Arab Emirates': 152.0,
 'United Kingdom of Great Britain and Northern Ireland': 153.0,
 'United Republic of Tanzania': 154.0,
 'United States of America': 155.0,
 'Uruguay': 156.0,
 'Uzbekistan': 157.0,
 'Venezuela (Bolivarian Republic of)': 158.0,
 'Viet Nam': 159.0,
 'Yemen': 160.0,
 'Zambia': 161.0,
 'Zimbabwe': 162.0}

In [271]:
def impute_medians(df):
    imputer_dict = {}
    for c in df.country.unique():
        df_temp = df.query("country == @c")
        c_imputer = SimpleImputer(strategy="median")
        df_temp_imp = c_imputer.fit_transform(df_temp)
        
        
    weights = np.zeros(len(dists))
    weights[0] = 1

In [358]:
class GroupedMedianImputer:
    def __init__(self, group_col, value_cols):
        self.group_col = group_col
        self.value_cols = value_cols
        self.medians = None

    def fit(self, df):
        self.medians = df.groupby(self.group_col)[self.value_cols].median()
        #print(self.medians[0])

    def transform(self, df):
        if self.medians is None:
            raise Exception("The imputer has not been fitted yet.")
        
        def fillna_grouped(x):
            return x.fillna(self.medians.loc[x.name, col])

        for col in self.value_cols:
            df[col] = df.groupby(self.group_col)[col].transform(fillna_grouped)
        
        return df

    def fit_transform(self, df):
        self.fit(df)
        return self.transform(df)

In [359]:
gmi = GroupedMedianImputer(group_col='country', value_cols=X_train.drop(columns=["country","year"], axis=1).columns.to_list())
X_train_imp = gmi.fit_transform(X_train)

955      0.319478
1333    19.753651
186      5.226452
1821     2.339369
907      1.154616
          ...
1243     0.631190
3885    38.369150
746      0.129010
2568     1.152378
2918     5.840846
Name: %_of_agricultural_gva_produced_by_irrigated_agriculture, Length: 2266, dtype: float64
955      77.777778
1333    100.000000
186     100.000000
1821    100.000000
907      81.741573
           ...
1243    100.000000
3885    100.000000
746     100.000000
2568     32.688416
2918    100.000000
Name: %_of_agricultural_water_managed_area_equipped_for_irrigation, Length: 2266, dtype: float64
955      6.171797
1333     6.814921
186     17.215069
1821     9.507728
907     22.948583
          ...
1243     6.579920
3885     3.618223
746     63.406771
2568    44.924602
2918    63.161004
Name: %_of_total_country_area_cultivated, Length: 2266, dtype: float64
955      0.071900
1333     0.600717
186      0.085687
1821     1.503333
907      0.595300
          ...
1243     0.050000
3885    16.710000
746      0.004700
2568     5.510000
2918     0.121636
Name: agricultural_water_withdrawal, Length: 2266, dtype: float64
955     0.005604
1333    0.948551
186     0.110280
1821    4.896851
907     0.707511
          ...
1243    0.045455
3885    1.261132
746     0.391667
2568    1.925227
2918    0.991331
Name: agricultural_water_withdrawal_as_%_of_total_renewable_water_resources, Length: 2266, dtype: float64
955     10.517847
1333    36.476468
186      2.506941
1821    72.742838
907     41.964894
          ...
1243     2.201418
3885    73.852110
746     47.000000
2568    44.168337
2918    10.347836
Name: agricultural_water_withdrawal_as_%_of_total_water_withdrawal, Length: 2266, dtype: float64
955     19.268473
1333     8.526235
186      1.416392
1821    14.367958
907     22.677046
          ...
1243     2.379723
3885     2.150784
746     28.956646
2568    19.990255
2918    16.298714
Name: agriculture_value_added_%_gdp, Length: 2266, dtype: float64
955     14472.0
1333      475.0
186      1444.0
1821     5518.0
907      7400.0
         ...
1243     2225.0
3885     3300.0
746       118.0
2568    41500.0
2918     2138.0
Name: cultivated_area_arable_land_plus_permanent_crops, Length: 2266, dtype: float64
955        0.671006
1333     846.006665
186      255.925825
1821     733.697159
907     1899.659224
           ...
1243    3548.721236
3885    5456.608721
746        0.000000
2568     287.218355
2918     270.516097
Name: dam_capacity_per_capita, Length: 2266, dtype: float64
955     29.851910
1333     8.210958
186     29.214929
1821    32.573290
907      8.676016
          ...
1243     2.727273
3885    39.245283
746      0.000000
2568    22.781272
2918    86.797066
Name: dependency_ratio, Length: 2266, dtype: float64
955     4.033751e+10
1333    1.762739e+10
186     3.886715e+11
1821    1.653357e+10
907     2.422491e+10
            ...
1243    1.971255e+11
3885    2.040437e+11
746     7.946217e+08
2568    5.684988e+11
2918    3.117982e+09
Name: gross_domestic_product, Length: 2266, dtype: float64
955     0.0
1333    0.0
186     0.0
1821    0.0
907     0.0
       ...
1243    0.0
3885    0.0
746     0.0
2568    0.0
2918    0.0
Name: groundwater_accounted_inflow, Length: 2266, dtype: float64
955     0.0
1333    0.0
186     0.0
1821    0.0
907     0.0
       ...
1243    0.0
3885    0.0
746     0.0
2568    0.0
2918    0.0
Name: groundwater_entering_the_country_total, Length: 2266, dtype: float64
955     0.146800
1333    0.251489
186     2.717667
1821    0.098462
907     0.292667
          ...
1243    1.814564
3885    0.793300
746     0.000500
2568    1.965000
2918    0.904240
Name: industrial_water_withdrawal, Length: 2266, dtype: float64
955     0.464900
1333    0.794656
186     0.614656
1821    0.464846
907     0.530600
          ...
1243    0.406700
3885    5.123000
746     0.004800
2568    5.000000
2918    0.149600
Name: municipal_water_withdrawal, Length: 2266, dtype: float64
955     1571.0
1333    1140.0
186     1126.0
1821     902.1
907     1187.0
         ...
1243     518.3
3885    1813.0
746     2304.0
2568    1295.0
2918     541.3
Name: national_rainfall_index, Length: 2266, dtype: float64
955      33.600781
1333     57.895423
186      99.114652
1821     58.155554
907      60.800003
           ...
1243     15.502499
3885     31.672735
746     344.771628
2568    190.961965
2918    123.130251
Name: population_density, Length: 2266, dtype: float64
955     3.058
1333    1.778
186     1.778
1821    1.356
907     2.648
        ...
1243    1.778
3885    1.540
746     1.778
2568    2.131
2918    1.778
Name: ratio_between_rainfed_and_irrigated_yields, Length: 2266, dtype: float64
955     44637.912
1333     1714.022
186      3470.218
1821    26374.762
907     10433.268
          ...
1243      903.126
3885     3818.502
746       462.822
2568    93555.299
2918     2375.227
Name: rural_population, Length: 2266, dtype: float64
955      99.430632
1333      9.416769
186      33.031792
1821     63.255526
907      18.348575
           ...
1243     32.328595
3885    124.283970
746     148.547189
2568     58.732159
2918      1.183454
Name: industrial_water_use_efficiency, Length: 2266, dtype: float64
955     0.332431
1333    0.406943
186     3.147585
1821    0.082022
907     0.101336
          ...
1243    0.103025
3885    0.095626
746     0.050912
2568    0.201433
2918    0.400901
Name: irrigated_agriculture_water_use_efficiency, Length: 2266, dtype: float64
955      30.516892
1333     11.695392
186     374.909008
1821     49.148936
907      20.688576
           ...
1243    310.328165
3885     16.353077
746      74.279668
2568     52.847097
2918     17.475642
Name: services_water_use_efficiency, Length: 2266, dtype: float64
955     42.141050
1333     7.229801
186     93.761878
1821    14.128355
907     11.566393
          ...
1243    84.124699
3885     8.130768
746     43.105529
2568    30.521369
2918     3.175944
Name: water_use_efficiency, Length: 2266, dtype: float64
955     383.00
1333      8.35
186      22.70
1821     10.00
907       4.30
         ...
1243      3.00
3885    495.00
746       0.00
2568     65.20
2918      9.20
Name: surface_water_entering_the_country_total, Length: 2266, dtype: float64
955       3.301
1333     11.910
186      77.700
1821      8.900
907      13.200
         ...
1243     27.000
3885    160.000
746       0.000
2568      2.900
2918     10.230
Name: surface_water_leaving_the_country_to_other_countries_total, Length: 2266, dtype: float64
955       13.500000
1333     487.710000
186      116.070000
1821     106.297727
907       89.000000
           ...
1243      87.150000
3885    1055.300000
746        0.130000
2568    1013.050000
2918     267.650000
Name: total_agricultural_water_managed_area, Length: 2266, dtype: float64
955     234486.0
1333      6970.0
186       8388.0
1821     58037.0
907      32246.0
          ...
1243     33815.0
3885     91205.0
746        186.1
2568     92377.0
2918      3385.0
Name: total_area_of_the_country_excl_coastal_water, Length: 2266, dtype: float64
955       0.052868
1333      3.413900
186       2.127700
1821     24.763555
907      37.243900
           ...
1243     18.603000
3885    157.625700
746       0.000000
2568     50.666735
2918      1.127500
Name: total_dam_capacity, Length: 2266, dtype: float64
955     900.00
1333     58.13
186      55.00
1821     20.70
907      76.84
         ...
1243    107.00
3885    805.00
746       1.20
2568    221.00
2918      1.62
Name: total_internal_renewable_water_resources, Length: 2266, dtype: float64
955     11422.895954
1333    14405.333319
186      6615.556879
1821      613.301732
907      3919.294564
            ...
1243    20411.394518
3885    27867.092868
746      1870.265889
2568     1252.799426
2918      388.679447
Name: total_internal_renewable_water_resources_per_capita, Length: 2266, dtype: float64
955      78789.127
1333      4035.311
186       8313.737
1821     33751.739
907      19605.569
           ...
1243      5242.170
3885     28887.118
746        641.620
2568    176404.934
2918      4167.959
Name: total_population, Length: 2266, dtype: float64
955     421.00
1333     17.23
186       6.00
1821      3.50
907      37.84
         ...
1243      2.20
3885    227.00
746       1.00
2568     87.00
2918      1.30
Name: total_renewable_groundwater, Length: 2266, dtype: float64
955     16283.972787
1333    15693.957665
186      9345.977627
1821      909.582763
907      4291.637748
            ...
1243    20983.676607
3885    45868.196336
746      1870.265889
2568     1622.403600
2918     2943.886924
Name: total_renewable_water_resources_per_capita, Length: 2266, dtype: float64
955      0.683600
1333     1.646862
186      3.418010
1821     2.066641
907      1.418567
          ...
1243     2.271264
3885    22.626300
746      0.010000
2568    12.475000
2918     1.175476
Name: total_water_withdrawal, Length: 2266, dtype: float64
955       8.676324
1333    408.112906
186     411.127959
1821     61.230653
907      72.355292
           ...
1243    433.267865
3885    783.266091
746      15.585549
2568     70.717977
2918    282.026854
Name: total_water_withdrawal_per_capita, Length: 2266, dtype: float64
955     34098.241
1333     2278.324
186      4841.565
1821     6839.247
907      9064.718
          ...
1243     4339.059
3885    28562.719
746       178.798
2568    82905.203
2918     1791.110
Name: urban_population, Length: 2266, dtype: float64
955      81.1
1333    100.0
186     100.0
1821     86.6
907      92.4
        ...
1243    100.0
3885     95.0
746      93.5
2568     80.6
2918     96.8
Name: urban_population_with_access_to_safe_drinking_water, Length: 2266, dtype: float64
955     383.00
1333      5.20
186      22.70
1821     10.00
907       7.30
         ...
1243      3.00
3885    520.00
746       0.00
2568     65.20
2918     10.65
Name: water_resources_total_external_renewable, Length: 2266, dtype: float64

In [362]:
country_ids['Norway']

110.0

In [363]:
X_train_imp.query("country == 110.0").sort_values("year")

,country,year,%_of_agricultural_gva_produced_by_irrigated_agriculture,%_of_agricultural_water_managed_area_equipped_for_irrigation,%_of_total_country_area_cultivated,agricultural_water_withdrawal,agricultural_water_withdrawal_as_%_of_total_renewable_water_resources,agricultural_water_withdrawal_as_%_of_total_water_withdrawal,agriculture_value_added_%_gdp,cultivated_area_arable_land_plus_permanent_crops,...,total_internal_renewable_water_resources,total_internal_renewable_water_resources_per_capita,total_population,total_renewable_groundwater,total_renewable_water_resources_per_capita,total_water_withdrawal,total_water_withdrawal_per_capita,urban_population,urban_population_with_access_to_safe_drinking_water,water_resources_total_external_renewable
2617,110,2003,4.886616,100.0,2.274261,0.7456,0.189720,28.913153,1.308039,876.0000,...,382.0,83586.682672,4570.106,96.0,85993.629032,2.578757,564.266374,3522.836,100.0,11.0
2618,110,2004,4.886616,100.0,2.269069,0.8892,0.226260,31.651208,1.386468,874.0000,...,382.0,83075.733317,4598.214,96.0,85467.966476,2.809371,610.970135,3558.958,100.0,11.0
2619,110,2005,8.564728,100.0,2.250896,0.7321,0.186285,26.725945,1.403426,867.0000,...,382.0,82463.295199,4632.364,96.0,84837.892704,2.739286,591.336457,3598.210,100.0,11.0
2620,110,2006,9.720031,100.0,2.240511,0.8449,0.214987,28.746895,1.404447,863.0000,...,382.0,81746.306544,4672.994,96.0,84100.257779,2.939100,628.954371,3642.666,100.0,11.0
2622,110,2008,10.025886,100.0,2.205982,0.8449,0.214987,28.793430,1.128001,849.7000,...,382.0,80066.753035,4771.019,96.0,82372.340165,2.934350,615.036327,3746.810,100.0,11.0
2623,110,2009,9.182042,100.0,2.179397,0.8449,0.214987,29.722789,1.300319,839.4600,...,382.0,79140.673168,4826.848,96.0,81419.593076,2.842600,588.914339,3804.552,100.0,11.0
2625,110,2011,6.967313,100.0,2.135106,0.8449,0.214987,30.515025,1.344657,822.4000,...,382.0,77197.761669,4948.330,96.0,79420.733864,2.768800,559.542310,3931.111,100.0,11.0
2626,110,2012,5.585959,100.0,2.119269,0.8449,0.214987,30.927194,1.127949,816.3000,...,382.0,76191.099244,5013.709,96.0,78385.083777,2.731900,544.886031,4003.301,100.0,11.0
2627,110,2013,4.187273,100.0,1.296750,0.8449,0.214987,30.680126,1.315306,810.7539,...,382.0,75204.918638,5079.455,96.0,77370.505300,2.753900,542.164464,4076.195,100.0,11.0
2628,110,2014,4.187273,100.0,1.297351,0.8449,0.214987,30.404117,1.442843,811.1300,...,382.0,74286.331023,5142.265,96.0,76425.466210,2.778900,540.403888,4147.805,100.0,11.0
2629,110,2015,4.187273,100.0,1.295805,0.8449,0.214987,31.135761,1.537558,810.1630,...,382.0,73463.855399,5199.836,96.0,75579.306732,2.713600,521.862613,4216.608,100.0,11.0
2630,110,2016,4.187273,100.0,1.292598,0.8449,0.214987,31.903485,2.092315,808.1580,...,382.0,72748.754558,5250.949,96.0,74843.613983,2.648300,504.346929,4281.776,100.0,11.0
2631,110,2017,4.187273,100.0,2.088525,0.8449,0.214987,31.394917,1.976463,804.5060,...,382.0,72125.469618,5296.326,96.0,74202.381047,2.691200,508.125822,4343.569,100.0,11.0
2632,110,2018,4.187273,100.0,2.093111,0.8449,0.214987,31.394917,1.862996,806.2830,...,382.0,71562.892355,5337.962,96.0,73623.603915,2.691200,504.162450,4403.040,100.0,11.0

inspect for scales

In [115]:
len(X_train.columns)

40

In [ ]:
df.loc[index_list, colname] = df.colname.median

In [256]:
# fig, axs = plt.subplots(10,4, figsize=(20,30))

# for i, c in enumerate(X_train.columns):
#     ax = axs.flat[i]
#     if c in unit_dict:
#         unit_str = str(unit_dict[c])
#     else:   unit_str = '-'
#     sns.histplot(X_train[c], bins=50, ax=ax)
#     ax.set_title(unit_str)
# fig.tight_layout()

In [257]:
# fig, axs = plt.subplots(5,8, figsize=(20,30))

# for i, c in enumerate(X_train.columns):
#     if c in ['country', 'year']:  continue
#     print(c)
#     ax = axs.flat[i]
#     if c in unit_dict:
#         unit_str = str(unit_dict[c])
#     else:   unit_str = '-'
#     sns.boxplot(y=X_train[c], ax=ax)
#     ax.set_title(unit_str)
# fig.tight_layout()

In [258]:
# type_list = ["none", "log", "sqrt", "cbrt"]
# for col in X_train.columns[2:]:
#     #print(col)
#     fig, axs = plt.subplots(1,4, figsize=(16,4))
#     sns.histplot(X_train[[col]], ax=axs[0])
#     sns.histplot(np.log(X_train[[col]]), ax=axs[1])
#     sns.histplot(np.sqrt(X_train[[col]]), ax=axs[2])
#     sns.histplot(np.power(X_train[[col]], 1./3.), ax=axs[3])
#     fig.suptitle(col)
#     ax
#     for i, ax in enumerate(axs):
#         ax.legend([])
#         ax.set_title(type_list[i])

transform features

In [168]:
transformation_dict = { "log": ["agricultural_water_withdrawal","agricultural_water_withdrawal_as_%_of_total_renewable_water_resources",        "cultivated_area_arable_land_plus_permanent_crops", "dam_capacity_per_capita", "groundwater_entering_the_country_total", "industrial_water_withdrawal", "municipal_water_withdrawal", "population_density", "ratio_between_rainfed_and_irrigated_yields", "rural_population", "industrial_water_use_efficiency","irrigated_agriculture_water_use_efficiency", "services_water_use_efficiency","water_use_efficiency","surface_water_entering_the_country_total", "surface_water_leaving_the_country_to_other_countries_total", "total_agricultural_water_managed_area","total_area_of_the_country_excl_coastal_water", "total_dam_capacity", "total_internal_renewable_water_resources", "total_internal_renewable_water_resources_per_capita", "total_population", "total_renewable_groundwater", "total_renewable_water_resources_per_capita", "total_water_withdrawal", "urban_population", "water_resources_total_external_renewable"
],
                        "square_root": ["national_rainfall_index"],
                        "cube_root": ["%_of_agricultural_gva_produced_by_irrigated_agriculture", "%_of_total_country_area_cultivated",                  "agriculture_value_added_%_gdp", "total_water_withdrawal_per_capita"]}